///////////////////////////////////////////////////////////////////////
/// Copyright (c) 1988-2017 $organization$
///
/// This software is provided by the author and contributors ``as is'' 
/// and any express or implied warranties, including, but not limited to, 
/// the implied warranties of merchantability and fitness for a particular 
/// purpose are disclaimed. In no event shall the author or contributors 
/// be liable for any direct, indirect, incidental, special, exemplary, 
/// or consequential damages (including, but not limited to, procurement 
/// of substitute goods or services; loss of use, data, or profits; or 
/// business interruption) however caused and on any theory of liability, 
/// whether in contract, strict liability, or tort (including negligence 
/// or otherwise) arising in any way out of the use of this software, 
/// even if advised of the possibility of such damage.
///
///   File: main_opt.hpp
///
/// Author: $author$
///   Date: 6/19/2017
///////////////////////////////////////////////////////////////////////
#ifndef _NADIR_APP_CONSOLE_NETWORK_MAIN_OPT_HPP
#define _NADIR_APP_CONSOLE_NETWORK_MAIN_OPT_HPP

#include "nadir/console/getopt/main.hpp"

///////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////
#define NADIR_APP_CONSOLE_NETWORK_MAIN_CLIENT_OPT "client"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_CLIENT_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_NONE
#define NADIR_APP_CONSOLE_NETWORK_MAIN_CLIENT_OPTARG_RESULT 0
#define NADIR_APP_CONSOLE_NETWORK_MAIN_CLIENT_OPTARG ""
#define NADIR_APP_CONSOLE_NETWORK_MAIN_CLIENT_OPTUSE "Run as client"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_CLIENT_OPTVAL_S "c"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_CLIENT_OPTVAL_C 'c'
#define NADIR_APP_CONSOLE_NETWORK_MAIN_CLIENT_OPTION \
   {NADIR_APP_CONSOLE_NETWORK_MAIN_CLIENT_OPT, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_CLIENT_OPTARG_REQUIRED, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_CLIENT_OPTARG_RESULT, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_CLIENT_OPTVAL_C}, \

#define NADIR_APP_CONSOLE_NETWORK_MAIN_SERVER_OPT "server"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_SERVER_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_NONE
#define NADIR_APP_CONSOLE_NETWORK_MAIN_SERVER_OPTARG_RESULT 0
#define NADIR_APP_CONSOLE_NETWORK_MAIN_SERVER_OPTARG ""
#define NADIR_APP_CONSOLE_NETWORK_MAIN_SERVER_OPTUSE "Run as server"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_SERVER_OPTVAL_S "s"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_SERVER_OPTVAL_C 's'
#define NADIR_APP_CONSOLE_NETWORK_MAIN_SERVER_OPTION \
   {NADIR_APP_CONSOLE_NETWORK_MAIN_SERVER_OPT, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_SERVER_OPTARG_REQUIRED, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_SERVER_OPTARG_RESULT, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_SERVER_OPTVAL_C}, \

#define NADIR_APP_CONSOLE_NETWORK_MAIN_HOST_OPT "host"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_HOST_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define NADIR_APP_CONSOLE_NETWORK_MAIN_HOST_OPTARG_RESULT 0
#define NADIR_APP_CONSOLE_NETWORK_MAIN_HOST_OPTARG "string"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_HOST_OPTUSE "Host name or address"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_HOST_OPTVAL_S "o:"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_HOST_OPTVAL_C 'o'
#define NADIR_APP_CONSOLE_NETWORK_MAIN_HOST_OPTION \
   {NADIR_APP_CONSOLE_NETWORK_MAIN_HOST_OPT, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_HOST_OPTARG_REQUIRED, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_HOST_OPTARG_RESULT, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_HOST_OPTVAL_C}, \

#define NADIR_APP_CONSOLE_NETWORK_MAIN_PORT_OPT "port"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_PORT_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define NADIR_APP_CONSOLE_NETWORK_MAIN_PORT_OPTARG_RESULT 0
#define NADIR_APP_CONSOLE_NETWORK_MAIN_PORT_OPTARG "number"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_PORT_OPTUSE "Port number"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_PORT_OPTVAL_S "p:"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_PORT_OPTVAL_C 'p'
#define NADIR_APP_CONSOLE_NETWORK_MAIN_PORT_OPTION \
   {NADIR_APP_CONSOLE_NETWORK_MAIN_PORT_OPT, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_PORT_OPTARG_REQUIRED, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_PORT_OPTARG_RESULT, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_PORT_OPTVAL_C}, \

#define NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPT "family"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTARG_RESULT 0
#define NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTARG_LOCAL_C "l"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTARG_LOCAL "local"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTARG_IPV4_C "4"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTARG_IPV4 "ipv4"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTARG_IPV6_C "6"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTARG_IPV6 "ipv6"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTARG "{ "\
    "(" NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTARG_LOCAL_C ")" \
    NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTARG_LOCAL " | " \
    "(" NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTARG_IPV4_C ")" \
    NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTARG_IPV4 " | " \
    "(" NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTARG_IPV6_C ")" \
    NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTARG_IPV6 " }"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTUSE "Address family"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTVAL_S "f:"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTVAL_C 'f'
#define NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTION \
   {NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPT, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTARG_REQUIRED, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTARG_RESULT, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTVAL_C}, \

#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPT "transport"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_RESULT 0
#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_RAW_C "r"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_RAW "raw"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_STREAM_C "s"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_STREAM "stream"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_DGRAM_C "d"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_DGRAM "dgram"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_TCP_C "t"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_TCP "tcp"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_UDP_C "u"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_UDP "udp"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG "{ " \
    "(" NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_RAW_C ")" \
    NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_RAW " | " \
    "(" NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_STREAM_C ")" \
    NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_STREAM "/" \
    "(" NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_TCP_C ")" \
    NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_TCP " | " \
    "(" NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_DGRAM_C ")" \
    NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_DGRAM "/" \
    "(" NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_UDP_C ")" \
    NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_UDP " }"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTUSE "Transport type"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTVAL_S "t:"
#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTVAL_C 't'
#define NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTION \
   {NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPT, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_REQUIRED, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTARG_RESULT, \
    NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTVAL_C}, \

///////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////
#define NADIR_APP_CONSOLE_NETWORK_MAIN_OPTIONS_CHARS \
   NADIR_APP_CONSOLE_NETWORK_MAIN_CLIENT_OPTVAL_S \
   NADIR_APP_CONSOLE_NETWORK_MAIN_SERVER_OPTVAL_S \
   NADIR_APP_CONSOLE_NETWORK_MAIN_HOST_OPTVAL_S \
   NADIR_APP_CONSOLE_NETWORK_MAIN_PORT_OPTVAL_S \
   NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTVAL_S \
   NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTVAL_S \
   NADIR_CONSOLE_GETOPT_MAIN_OPTIONS_CHARS

#define NADIR_APP_CONSOLE_NETWORK_MAIN_OPTIONS_OPTIONS \
   NADIR_APP_CONSOLE_NETWORK_MAIN_CLIENT_OPTION \
   NADIR_APP_CONSOLE_NETWORK_MAIN_SERVER_OPTION \
   NADIR_APP_CONSOLE_NETWORK_MAIN_HOST_OPTION \
   NADIR_APP_CONSOLE_NETWORK_MAIN_PORT_OPTION \
   NADIR_APP_CONSOLE_NETWORK_MAIN_FAMILY_OPTION \
   NADIR_APP_CONSOLE_NETWORK_MAIN_TRANSPORT_OPTION \
   NADIR_CONSOLE_GETOPT_MAIN_OPTIONS_OPTIONS

///////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////
#define NADIR_APP_CONSOLE_NETWORK_MAIN_ARGS 0
#define NADIR_APP_CONSOLE_NETWORK_MAIN_ARGV

namespace nadir {
namespace app {
namespace console {
namespace network {

} // namespace network 
} // namespace console 
} // namespace app 
} // namespace nadir 

#endif // _NADIR_APP_CONSOLE_NETWORK_MAIN_OPT_HPP 
